export const PROJECTS = [
  {
    title: "Haven: AI Chat",
    description: `Designed and built "Haven," an AI-powered chat companion web app using Next.js and tRPC, deployed via Vercel. Integrated a custom large language model hosted on Google Cloud Platform, serving over 200 users with a smooth and intuitive chat interface.`,
    img: "/assets/haven-chat.jpeg",
    from: "May 2023",
    to: "January 2025",
    label: "Visit Website",
    tags: ["Next.js", "tRPC", "GCP", "React"],
  },
  {
    title: "Covid-19 Japan Tracker",
    description: `Built an interactive COVID-19 dashboard as part of a Mapbox certification. Visualized Japan-wide pandemic statistics including active, testing, recovery, and death cases using React, Mapbox JS, and D3.js.`,
    img: "/assets/mapbox-exam/covid-japan.jpg",
    href: "https://github.com/cth1011/covid-japan",
    from: "Sept 2020",
    to: "Oct 2020",
    label: "Visit Github Repo",
    tags: ["React", "Mapbox JS", "d3.js"],
  },
  {
    title: "Hermosa Beauty Store",
    description: `Launched a Shopify-based e-commerce store for a local beauty brand in the Philippines. Configured product catalog with over 200 SKUs and implemented custom Liquid templates to enhance user experience and visual branding.`,
    img: "/assets/hermosa.png",
    href: "https://hermosabeautystore.com/",
    from: "June 2020",
    to: "July 2020",
    label: "Visit Website",
    tags: ["Shopify", "Liquid", "CSS"],
  },
  {
    title: "Inaccessible HIV Centers",
    description: `Developed a geospatial web app that maps inaccessible HIV treatment centers across the Philippines. Used Mapbox JS to visualize location data and support public health decision-making in underserved areas.`,
    img: "/assets/HIV.png",
    from: "Sept 2018",
    to: "Dec 2018",
    tags: ["Mapbox JS", "Javascript"],
    href: "https://stories.thinkingmachin.es/doh-hiv-centers-access/",
  },
];